USE footballManager;

INSERT INTO equipe (id_equipe,nom_equipe) VALUES 
(1,"France"),
(2,"Allemagne"),
(3,"Italie"),
(4,"Angleterre"),
(5,"Espagne");

INSERT INTO joueur (nom_joueur, id_equipe) VALUES 
("Benzema", 1),
("Griezmann", 1),
("Pogba", 1),
("Payet", 1),
("Giroud", 1),
("Lloris", 1),
("Evra", 1),
("Sissoko", 1),
("Ben Arfa", 1),
("Gignac", 1),
("Martial", 1),
("Valbuena", 1),
("Matuidi", 1),
("Gameiro", 1),
("Varane", 1),
("Koscielny", 1);

INSERT INTO joueur (nom_joueur, id_equipe) VALUES 
("Özil", 2),
("Neuer", 2),
("Müller", 2),
("Götze", 2),
("Reus", 2),
("Kroos", 2),
("Podolski", 2),
("Boateng", 2),
("Draxler", 2),
("Hummels", 2),
("Khedira", 2),
("Kimmich", 2),
("Schürrle", 2),
("Mustafi", 2),
("Sané", 2),
("Hector", 2);

INSERT INTO joueur (nom_joueur, id_equipe) VALUES 
("Bouffon", 3),
("Pellè", 3),
("Bonucci", 3),
("Chiellini", 3),
("Martins", 3),
("Rossi", 3),
("Marchisio", 3),
("Insigne", 3),
("Zaza", 3),
("Shaarawy", 3),
("Candreva", 3),
("Giovinco", 3),
("Barzagli", 3),
("Immobile", 3),
("Giaccherini", 3),
("Florenzi", 3);
INSERT INTO joueur (nom_joueur, id_equipe) VALUES 
("Rooney", 4),
("Vardy", 4),
("Hart", 4),
("Kane", 4),
("Rashford", 4),
("Sturridge", 4),
("Sterling", 4),
("Wilshere", 4),
("Lallana", 4),
("Alli", 4),
("Walcott", 4),
("Henderson", 4),
("Dier", 4),
("Cahill", 4),
("Stones", 4),
("Smalling", 4);

INSERT INTO joueur (nom_joueur, id_equipe) VALUES 
("Casillas", 5),
("Piqué", 5),
("Ramos", 5),
("Iniesta", 5),
("Morata", 5),
("Costa", 5),
("de Gea", 5),
("Fàbregas", 5),
("Silva", 5),
("Isco", 5),
("Busquets", 5),
("Nolito", 5),
("Mata", 5),
("Pedro", 5),
("Alba", 5),
("Koke", 5);